### ISSUE TITLE
Add test tzBTC and USDT to faucet for Batcher

### ISSUE THREAD

**Issue by glottologist** [marigold-dev/faucet-bot#1]
To support Batcher we need to add the two test tokens used in the batching pool to be freely available through the faucet.  The token details for Ghostnet and Kathmandunet are: 

Ghostnet:
TZBTC_HASH = KT1XLyXAe5FWMHnoWa98xZqgDUyyRms2B3tG
USDT_HASH = KT1H9hKtcqcMHuCoaisu8Qy7wutoUPFELcLm

Kathmandunet: 
TZBTC_HASH = KT1EGB9ZquErCN3dNvPurmNBuKCAi8pc1ce7
USDT_HASH = KT1QVV45Rj9r6WbjLczoDxViP9s1JpiCsxVF

Please ping me if you need the test tokens transferred to a particular address.

**Comment by zamrokk** [comment]
@glottologist 

Could you please give/allow the maximum of tokens to these administrators (from where tokens will be freed)

Ghostnet : tz1cxZNE811exSe9Z99wYJwqHEnpRWbQswDN
Kathmandunet : tz1KkeNrP9YeL4NzU9ha5yuvxv8NYpWNd2LY 


Thank you

**Comment by zamrokk** [comment]
done, and deployed
